version: '3'
services:
  backend:
    image: ns-backend-docker.jar
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
  mysql:
    container_name: mysqldatabase
    image: mysql:5.5.57
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=nsdatabase
      - MYSQL_ROOT_PASSWORD=root
